### ISSUE TITLE
CompilerPass with symfony ContainerAwareCommand

### ISSUE THREAD

**Issue by gtrias** [mmoreram/SimpleDoctrineMapping#22]
I'm trying this bundle to develop reusable bundles and I found that everything works as expected but Command related code. It seems the CompilerPass is ignored when you use EntityManager inside a ContainerAwareCommand:

Example:

```
class ExpireTokenCommand extends ContainerAwareCommand
{
    protected function execute(...)
    {
        $em = $this->getContainer()->get('doctrine.orm.entity_manager');
        $em->getRepository("FooBarBundle:SomeEntity");
    }
}
```

It returns 

```
 Unknown Entity namespace alias 'FooBarBundle'
```

Bot the other functional tests are passing

Any idea why?

**Comment by mmoreram** [comment]
@gtrias Sorry for the delay!

Let me take a look :)

**Comment by mmoreram** [comment]
@gtrias The way the entity manager is loaded, like the container, should never change the behavior of your application, and Symfony is designed for that.

Can you try the same lines inside a Controller?

**Comment by gtrias** [comment]
thx @mmoreram 

Same lines inside a Controller causes the same error.

I found the error happens when I'm calling getRepository passing the namespace alias as first parameter instead of the real namespace. If I call using the real namespace it works well, as the example:

Changing this:
```
$em->getRepository("FooBarBundle:SomeEntity");
```
For this:

```
$em->getRepository("Foo\BarBundle\Entity\SomeEntity");
```
Where is suposed to be defined the entity namespace alias?

**Comment by mmoreram** [comment]
WOW!

Let me do some tests and check the correctness of the implementation. I need to find out where this alias is defined!

Thanks for your feedback!

**Comment by gtrias** [comment]
Hi @mmoreram ,

I've found that this error is only raised when ``doctrine.orm.auto_mapping`` is set to ``false`` as you say in the Readme.

When ``auto_mapping`` is set to true everything works as expected. So I guess auto_mapping is the responsible to create the namespaces alias. Is there anything bad to have auto_mapping enabled with this workaround?

**Comment by mmoreram** [comment]
@gtrias found and solved. Uploading now and will create a new version.

**Comment by gtrias** [comment]
Thx @mmoreram :)
