### ISSUE TITLE
MappingDriverChain

### ISSUE THREAD

**Issue by xphere** [mmoreram/SimpleDoctrineMapping#23]
I wonder what [`MappingDriverChain`](https://github.com/mmoreram/SimpleDoctrineMapping/blob/master/Mapping/MappingDriverChain.php) is really doing: Removing it (or just removing every method so they will be inherited from the parent) works the same in our code, which makes heavy usage of this functionality. Even more: this class assumes every `Driver` inherits from `FileDriver`, which fails when any manual mapping is done. Removing this class makes simple-mapping, manual-mapping and auto-mapping work out of the box. Am I missing something?

**Comment by mmoreram** [comment]
Absolutely true!
Fixed it and removed this class.

Thanks for this awesome alert, now this bundle is compatible with auto_mapping ^^
